### ISSUE TITLE
__init__() got an unexpected keyword argument service_log_path

### ISSUE THREAD

**Issue by meuchel** [robotframework/SeleniumLibrary#1419]
Since we updated robotframework and robotframework-seleniumlibrary we get following Message: __init__() got an unexpected keyword argument service_log_path

It seems that Version 4.0.0a2 does not work any more with firefox 65.0

1. What could be the workaround to use selenium  4.0.0a2 with firefox 65.0
2. which firefox version do we need to work with selenium 4.0.0a2

Remark, For some reason we can't alwas update to latest firefox, we need to use ff  65.0

geckodriver --version
geckodriver 0.24.0 ( 2019-01-28)

firefox --version
Mozilla Firefox 65.0

pip freeze | grep -e robotframework= -e obotframework-seleniumlibrary
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
robotframework==3.1.2
robotframework-seleniumlibrary==4.0.0a2

uname -a
Linux xxxxxxx 4.1.12-103.3.8.el7uek.x86_64 #2 SMP Mon Aug 21 17:27:54 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aaltat** [comment]
What version of Selenium you are using?

**Comment by meuchel** [comment]
Sorry, forgotten selenium itself:
pip freeze | grep selenium
robotframework-seleniumlibrary==4.0.0a2
**selenium==3.11.0**

**Comment by aaltat** [comment]
There is a bug in the SeleniumLibrary, not hard to fix, the Firefox WebDriver, in that Selenium version, does not yet support service_log_path argument: https://github.com/SeleniumHQ/selenium/blob/selenium-3.11.0/py/selenium/webdriver/firefox/webdriver.py

As a workaround, you could update Selenium to the latest version and the bug should not appear.

**Comment by aaltat** [comment]
This should be now fixed in the project master branch. Would it be possible to @meuchel  install directly from the master code line and give it a try?

**Comment by zoxed** [comment]
hey @aaltat, if i may take a little bit of your time .. i am facing the same problem but my selenium version is 6.0.0
i don't know from where to start

**Comment by emanlove** [comment]
@zoxed Its best to ask for support over in our Slack channel.

**Comment by ashokkumar7** [comment]
I have overcome this issue by adding python code with below driver initialization

Call Method    ${chrome options}    add_experimental_option    prefs    ${prefs}
    Call Method    ${chrome_options}    add_argument    --disable-dev-shm-usage  #disable page crash of chrome
    Call Method    ${chrome_options}    add_argument    --no-sandbox  #disable sandbox mode
    Call Method    ${chrome_options}    add_argument    --headless  #run with no web browser
    Call Method    ${chrome_options}    add_argument    --ignore-certificate-errors  #run with no web browser
	Call Method    ${chrome_options}    add_argument    --disable-gpu  #run with no web browser
	Call Method    ${chrome options}    add_argument    --ignore-ssl-errors

    Create Webdriver    Chrome    chrome_options=${chrome options}
    Create Webdriver    driver_name=Chrome    alias=google    chrome_options=${chrome_options}


and pyhon code as library reference in robot file

from robot.libraries.BuiltIn import BuiltIn

class headless_download(object):

    ROBOT_LIBRARY_VERSION = 1.0

    def __init__(self):
        pass

    def enable_download_in_headless_chrome(self, download_dir):
        """
        there is currently a "feature" in chrome where
        headless does not allow file download: https://bugs.chromium.org/p/chromium/issues/detail?id=696481
        This method is a hacky work-around until the official chromedriver support for this.
        Requires chrome version 62.0.3196.0 or above.
        """
        instance = BuiltIn().get_library_instance('SeleniumLibrary')
        driver = instance.driver
        print(download_dir)

        # add missing support for chrome "send_command"  to selenium webdriver
        driver.command_executor._commands["send_command"] = ("POST", '/session/$sessionId/chromium/send_command')

        params = {'cmd': 'Page.setDownloadBehavior', 'params': {'behavior': 'allow', 'downloadPath': download_dir}}
        command_result = driver.execute("send_command", params)
        print("response from browser:")
        for key in command_result:
            print("result:" + key + ":" + str(command_result[key]))

Thanks
Ashok

**Comment by YkpDeMiR** [comment]
${options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys
    Call Method    ${options}    add_argument    --disable-logging
    Create Webdriver    Chrome    options=${options}
    Go To    url
