### ISSUE TITLE
Some of the keywords won't work with the latest Selenium 2.46.1 -library

### ISSUE THREAD

**Issue by molsky** [robotframework/SeleniumLibrary#456]
![test](https://cloud.githubusercontent.com/assets/1943521/8820144/9644f274-305b-11e5-890b-bc8fdec034ae.png)
Our Jenkins build updated Selenium library automatically to version 2.46.1 and that caused all tests to fail. So far looks like the issue is with `Wait Until ...` -keywords.

Wait Until Page Contains Element id_password: `AttributeError: 'NoneType' object has no attribute 'id'`

Reproduced this with Linux and OSX with the Selenium==2.46.1 and Selenium2Library==1.7.1 (and RF 2.9 RC1).

**Comment by Chaser** [comment]
I also had the same issue with RF 2.8.7. Rolling back to Selenium python bindings 2.46.0 the issue is nonexistent.

**Comment by emanlove** [comment]
Going to see if I can find some time today to look at this. I am thinking we need to release a hot fix for this. Note the change log for selenium can be found [here](https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES)

**Comment by emanlove** [comment]
@hgarus's [change](https://github.com/rtomac/robotframework-selenium2library/commit/c0b12ef52f7d56ba185f350354b85aee37968383) has fixed this. I will see if I can get out a fix later today. In the meantime people should be able to patch their systems to fix this problem. Sorry for the issue and delay.

**Comment by just-be-dev** [comment]
Yeah, this was fixed yesterday but I didn't have time to push a release. It's already in master though.

@emanlove are you going to do the release, or would you like me to?

**Comment by emanlove** [comment]
I can do it sometime this evening, early evening.

**Comment by just-be-dev** [comment]
I can do it now if you'd like.

**Comment by just-be-dev** [comment]
Update is being tracked in #457.

**Comment by just-be-dev** [comment]
1.7.2 is out now. This should be fixed after you update. 

If you have any issues, let us know.
